"""
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example :
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
"""

#Solution 1:
class Solution(object):
    def findTheDifference(self, s, t):
        s = list(s)
        for char in t:
            try :
                s.remove(char)
            except :
                return char
        return s[0]
      
#Optimal Solution using bitwise (by : hi-malik) :
class Solution(object):
    def findTheDifference(self, s, t):
        c = 0
        for cs in s: c ^= ord(cs) 
        for ct in t: c ^= ord(ct)
        return chr(c)
      
"""
For the first solution, im using try and except to check if the char can be removed or not. If not, that mean the char is not exist in string. If char wasnt found 
until the very last of iteration, the string will be left with one char, then return that char. The optimal solution is using a xor operation in every iteration.
Basically, the xor operation will cancel the same string because in xor logic 1,1 = 0 and 0,0 = 0 so the char will be left with the answer.
"""
